# -*- coding: utf-8 -*-
"""csv_automation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y7kOck1XTNWqAvaI50O8zDwQN_dwadhV

# CSV AUTOMATION

## Reading a csv file, then updating the file each time the code runs
"""

import pandas as pd
import numpy as np
import glob
import os
from datetime import datetime

"""### Create the original data file to work with"""

# create a starting csv with datetime and run number as columns
# data = [[1, datetime.now().replace(microsecond=0)], [2, datetime.now().replace(microsecond=0)], [3, datetime.now().replace(microsecond=0)]]
# df = pd.DataFrame(data, columns=['run','date'])
# df.to_csv('original_csv.csv', index=False)
# df

"""### Read the most recent csv file into a dataframe, then append new line """

# find the most recent csv file in data folder
# print(os.getcwd())
# path = os.getcwd()
# os.chdir(path+'/data')
list_of_files = glob.glob('data/*.csv')
latest_file = max(list_of_files, key=os.path.getctime)

# read csv -> dataframe
df2 = pd.read_csv(latest_file)

# append new row to the end of the dataframe
df2.loc[len(df2)] = [df2['run'].iloc[-1]+1, datetime.now().replace(microsecond=0)]

# format the most recent datetime to work with file names
date = df2['date'].iloc[-1].strftime('%d-%m-%y_%H%M')

# save new csv with datetime at end of filename
df2.to_csv('data/new_%s.csv' % (date), index=False)

"""### Check the most recent csv file"""

# read latest csv file to make sure things are running fine
# list_of_files = glob.glob('/content/*.csv')  
# latest_file = max(list_of_files, key=os.path.getctime)
# pd.read_csv(latest_file)

