# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: csv-automation


on:
  push:
    
  schedule:
    - cron: '0 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Create new csv
      run: |
        python csv_automation.py
        
    - name: commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add . 
        git commit --allow-empty -m "Auto-update of the data packages" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: "main"
        github_token: ${{ secrets.G_TOKEN }}
      
    - name: Sending email report
      run: |
        python auto-email.py
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
